import {
  FaLinkedin,
  FaGithub,
  FaDev,
  FaStackOverflow,
  FaMedium,
  FaCog,
  FaEnvelope,
  FaSpinner,
  FaCheck,
  FaMoon,
  FaSun,
  FaReact,
  FaGitAlt,
  FaDocker,
  FaClipboardCheck,
  FaServer,
  FaHtml5,
} from "react-icons/fa";
import { FaHashnode } from "react-icons/fa6";
import { IoMdLink } from "react-icons/io";
import { GiHamburgerMenu } from "react-icons/gi";
import {
  SiJavascript,
  SiTypescript,
  SiRedux,
  SiRubyonrails,
  SiPostgresql,
  SiGraphql,
  SiTailwindcss,
  SiNextdotjs,
  SiExpress,
  SiMysql,
  SiJest,
  SiWebpack,
} from "react-icons/si";

const icons = {
  Github: FaGithub,
  LinkedIn: FaLinkedin,
  Dev: FaDev,
  StackOverflow: FaStackOverflow,
  Hashnode: FaHashnode,
  Medium: FaMedium,
  Settings: FaCog,
  Email: FaEnvelope,
  Connect: IoMdLink,
  Loading: FaSpinner,
  Check: FaCheck,
  Moon: FaMoon,
  Sun: FaSun,
  Hamburger: GiHamburgerMenu,
  Javascript: SiJavascript,
  React: FaReact,
  Typescript: SiTypescript,
  Redux: SiRedux,
  Rubyonrails: SiRubyonrails,
  Postgresql: SiPostgresql,
  Graphql: SiGraphql,
  Html5: FaHtml5,
  Tailwindcss: SiTailwindcss,
  GitAlt: FaGitAlt,
  Docker: FaDocker,
  Nextdotjs: SiNextdotjs,
  Express: SiExpress,
  Mysql: SiMysql,
  Jest: SiJest,
  Server: FaServer,
  ClipboardCheck: FaClipboardCheck,
  Webpack: SiWebpack,
};

export { icons as IconLibrary };
