import {
  FaLinkedin,
  FaGithub,
  FaDev,
  FaStackOverflow,
  FaMedium,
  FaCog,
  FaEnvelope,
  FaSpinner,
  FaCheck,
  FaMoon,
  FaSun,
  FaReact,
  FaGitAlt,
  FaDocker,
  FaClipboardCheck,
  FaServer,
  FaHtml5,
  FaSearch,
  FaExternalLinkAlt,
  FaCodeBranch,
  FaBitbucket
} from 'react-icons/fa'
import { FaHashnode } from 'react-icons/fa6'
import { IoMdLink, IoMdClose } from 'react-icons/io'
import { GiHamburgerMenu } from 'react-icons/gi'
import {
  SiJavascript,
  SiTypescript,
  SiRedux,
  SiRubyonrails,
  SiPostgresql,
  SiGraphql,
  SiTailwindcss,
  SiNextdotjs,
  SiExpress,
  SiMysql,
  SiJest,
  SiWebpack,
  SiNodedotjs,
  SiCypress,
  SiSupabase,
  SiPrisma,
  SiApollographql,
  SiStorybook,
  SiStyledcomponents,
  SiRubysinatra,
  SiRubygems,
  SiAutocad,
  SiKubernetes,
  SiJira,
  SiElasticsearch,
  SiJsonwebtokens,
  SiGooglecloud,
  SiStripe,
  SiVercel,
  SiNginx,
  SiGithubactions,
  SiCircleci,
  SiDatadog

} from 'react-icons/si'
import { TbWriting, TbSettingsAutomation } from 'react-icons/tb'
import { GoProjectRoadmap } from 'react-icons/go'
import { FiExternalLink } from 'react-icons/fi'

const icons = {
  Github: FaGithub,
  LinkedIn: FaLinkedin,
  Dev: FaDev,
  StackOverflow: FaStackOverflow,
  Hashnode: FaHashnode,
  Medium: FaMedium,
  Settings: FaCog,
  Email: FaEnvelope,
  Connect: IoMdLink,
  Loading: FaSpinner,
  Check: FaCheck,
  Moon: FaMoon,
  Sun: FaSun,
  Hamburger: GiHamburgerMenu,
  Javascript: SiJavascript,
  React: FaReact,
  Typescript: SiTypescript,
  Redux: SiRedux,
  Rubyonrails: SiRubyonrails,
  Postgresql: SiPostgresql,
  Graphql: SiGraphql,
  Html5: FaHtml5,
  Tailwindcss: SiTailwindcss,
  GitAlt: FaGitAlt,
  Docker: FaDocker,
  NextJs: SiNextdotjs,
  NodeJs: SiNodedotjs,
  Express: SiExpress,
  Mysql: SiMysql,
  Jest: SiJest,
  Server: FaServer,
  ClipboardCheck: FaClipboardCheck,
  Webpack: SiWebpack,
  search: FaSearch,
  externalLink: FaExternalLinkAlt,
  close: IoMdClose,
  projects: GoProjectRoadmap,
  collab: FaCodeBranch,
  SiCypress: SiCypress,
  SiSupabase: SiSupabase,
  SiPrisma: SiPrisma,
  SiApollo: SiApollographql,
  SiStorybook: SiStorybook,
  SiStyledcomponents: SiStyledcomponents,
  automation: TbSettingsAutomation,
  TbWriting,
  SiRubysinatra,
  SiRubygems,
  SiAutocad,
  SiKubernetes,
  SiJira,
  SiElasticsearch,
  SiJsonwebtokens,
  SiGooglecloud,
  SiStripe,
  SiVercel,
  SiNginx,
  SiGithubactions,
  SiCircleci,
  SiDatadog,
  link: FiExternalLink,
  FaBitbucket
}

export { icons as IconLibrary }
