// iconLibrary.ts
import { ComponentType } from 'react';

const icons: {
  [key: string]: () => Promise<{ default: ComponentType<{ size?: number; className?: string }> }>;
} = {
  Github: () => import('react-icons/fa').then((mod) => ({ default: mod.FaGithub })),
  LinkedIn: () => import('react-icons/fa').then((mod) => ({ default: mod.FaLinkedin })),
  Dev: () => import('react-icons/fa').then((mod) => ({ default: mod.FaDev })),
  StackOverflow: () => import('react-icons/fa').then((mod) => ({ default: mod.FaStackOverflow })),
  Hashnode: () => import('react-icons/fa6').then((mod) => ({ default: mod.FaHashnode })),
  Medium: () => import('react-icons/fa').then((mod) => ({ default: mod.FaMedium })),
  Settings: () => import('react-icons/fa').then((mod) => ({ default: mod.FaCog })),
  Email: () => import('react-icons/fa').then((mod) => ({ default: mod.FaEnvelope })),
  Connect: () => import('react-icons/io').then((mod) => ({ default: mod.IoMdLink })),
  Loading: () => import('react-icons/fa').then((mod) => ({ default: mod.FaSpinner })),
  Check: () => import('react-icons/fa').then((mod) => ({ default: mod.FaCheck })),
  Moon: () => import('react-icons/fa').then((mod) => ({ default: mod.FaMoon })),
  Sun: () => import('react-icons/fa').then((mod) => ({ default: mod.FaSun })),
  Hamburger: () => import('react-icons/gi').then((mod) => ({ default: mod.GiHamburgerMenu })),
  Javascript: () => import('react-icons/si').then((mod) => ({ default: mod.SiJavascript })),
  React: () => import('react-icons/fa').then((mod) => ({ default: mod.FaReact })),
  Typescript: () => import('react-icons/si').then((mod) => ({ default: mod.SiTypescript })),
  Redux: () => import('react-icons/si').then((mod) => ({ default: mod.SiRedux })),
  Rubyonrails: () => import('react-icons/si').then((mod) => ({ default: mod.SiRubyonrails })),
  Postgresql: () => import('react-icons/si').then((mod) => ({ default: mod.SiPostgresql })),
  Graphql: () => import('react-icons/si').then((mod) => ({ default: mod.SiGraphql })),
  Html5: () => import('react-icons/fa').then((mod) => ({ default: mod.FaHtml5 })),
  Tailwindcss: () => import('react-icons/si').then((mod) => ({ default: mod.SiTailwindcss })),
  GitAlt: () => import('react-icons/fa').then((mod) => ({ default: mod.FaGitAlt })),
  Docker: () => import('react-icons/fa').then((mod) => ({ default: mod.FaDocker })),
  NextJs: () => import('react-icons/si').then((mod) => ({ default: mod.SiNextdotjs })),
  NodeJs: () => import('react-icons/si').then((mod) => ({ default: mod.SiNodedotjs })),
  Express: () => import('react-icons/si').then((mod) => ({ default: mod.SiExpress })),
  Mysql: () => import('react-icons/si').then((mod) => ({ default: mod.SiMysql })),
  Jest: () => import('react-icons/si').then((mod) => ({ default: mod.SiJest })),
  Server: () => import('react-icons/fa').then((mod) => ({ default: mod.FaServer })),
  ClipboardCheck: () => import('react-icons/fa').then((mod) => ({ default: mod.FaClipboardCheck })),
  Webpack: () => import('react-icons/si').then((mod) => ({ default: mod.SiWebpack })),
  Search: () => import('react-icons/fa').then((mod) => ({ default: mod.FaSearch })),
  ExternalLink: () => import('react-icons/fa').then((mod) => ({ default: mod.FaExternalLinkAlt })),
  Close: () => import('react-icons/io').then((mod) => ({ default: mod.IoMdClose })),
  Projects: () => import('react-icons/go').then((mod) => ({ default: mod.GoProjectRoadmap })),
  Collab: () => import('react-icons/fa').then((mod) => ({ default: mod.FaCodeBranch })),
  SiCypress: () => import('react-icons/si').then((mod) => ({ default: mod.SiCypress })),
  SiSupabase: () => import('react-icons/si').then((mod) => ({ default: mod.SiSupabase })),
  SiPrisma: () => import('react-icons/si').then((mod) => ({ default: mod.SiPrisma })),
  SiApollo: () => import('react-icons/si').then((mod) => ({ default: mod.SiApollographql })),
  SiStorybook: () => import('react-icons/si').then((mod) => ({ default: mod.SiStorybook })),
  SiStyledcomponents: () => import('react-icons/si').then((mod) => ({ default: mod.SiStyledcomponents })),
  Automation: () => import('react-icons/tb').then((mod) => ({ default: mod.TbSettingsAutomation })),
  TbWriting: () => import('react-icons/tb').then((mod) => ({ default: mod.TbWriting })),
  SiRubysinatra: () => import('react-icons/si').then((mod) => ({ default: mod.SiRubysinatra })),
  SiRubygems: () => import('react-icons/si').then((mod) => ({ default: mod.SiRubygems })),
  SiAutocad: () => import('react-icons/si').then((mod) => ({ default: mod.SiAutocad })),
  SiKubernetes: () => import('react-icons/si').then((mod) => ({ default: mod.SiKubernetes })),
  SiJira: () => import('react-icons/si').then((mod) => ({ default: mod.SiJira })),
  SiElasticsearch: () => import('react-icons/si').then((mod) => ({ default: mod.SiElasticsearch })),
  SiJsonwebtokens: () => import('react-icons/si').then((mod) => ({ default: mod.SiJsonwebtokens })),
  SiGooglecloud: () => import('react-icons/si').then((mod) => ({ default: mod.SiGooglecloud })),
  SiStripe: () => import('react-icons/si').then((mod) => ({ default: mod.SiStripe })),
  SiVercel: () => import('react-icons/si').then((mod) => ({ default: mod.SiVercel })),
  SiNginx: () => import('react-icons/si').then((mod) => ({ default: mod.SiNginx })),
  SiGithubactions: () => import('react-icons/si').then((mod) => ({ default: mod.SiGithubactions })),
  SiCircleci: () => import('react-icons/si').then((mod) => ({ default: mod.SiCircleci })),
  SiDatadog: () => import('react-icons/si').then((mod) => ({ default: mod.SiDatadog })),
  Link: () => import('react-icons/fi').then((mod) => ({ default: mod.FiExternalLink })),
  FaBitbucket: () => import('react-icons/fa').then((mod) => ({ default: mod.FaBitbucket })),
};

export { icons as IconLibrary };